version: "3"

services:
  django:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: python manage.py runserver 0.0.0.0:3030
    volumes:
      - ./:/usr/src/lukaid-me-server/
    ports:
      - 3030:3030
    env_file: ${ENVFILE}

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${SQL_PORT}
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    command: -p ${SQL_PORT}

volumes:
  postgres_data:
