version: "3"

services:
  lm-nginx-prod:
    container_name: lm-nginx-prod
    build: ./nginx
    ports:
      - ${ENTRY_PORT}:${ENTRY_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/settings.conf:/etc/nginx/settings.conf
      - static-volume:/usr/src/lukaid-me-server/staticfiles/
    depends_on:
      - lm-django-prod
      - lm-database-prod
    networks:
      - lm-prod

  lm-django-prod:
    container_name: lm-django-prod
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}
    volumes:
      - static-volume:/usr/src/lukaid-me-server/staticfiles/
    expose:
      - ${DJANGO_PORT}
    env_file: ${ENVFILE}
    depends_on:
      - lm-database-prod
    networks:
      - lm-prod

  lm-database-prod:
    container_name: lm-database-prod
    image: postgres:16.2-alpine
    volumes:
      - lukaid-me-data:/var/lib/postgresql/data-prod/
    expose:
      - ${SQL_PORT}
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    command: -p ${SQL_PORT}
    networks:
      - lm-prod

volumes:
  lukaid-me-data:
  static-volume:

networks:
  lm-prod:
    driver: bridge
