# Generated by Django 4.2.11 on 2024-04-22 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='written_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 22, 23, 2, 54, 469302), null=True),
        ),
    ]
