# Generated by Django 4.2.11 on 2024-04-23 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_written_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 23, 14, 9, 7, 488317), null=True),
        ),
    ]
