# Generated by Django 4.2.11 on 2024-04-23 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_written_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
